### PR TITLE
Fix setup.py installation for python 3

### PR DESCRIPTION
**Pull request by hargup**

### CODE REVIEW

**Comment by hargup** [comment]
cc @AllenDowney

**Comment by dgomes** [comment]
This PR request is necessary to support proper install of swampy in python 3 environments

(A new pip release is also necessary)

**Comment by AllenDowney** [comment]
Thanks!

**Comment by dgomes** [comment]
Thanks @AllenDowney, if only you could also release a new pip, that would be great! :)

**Pull request merged**
